//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreMigrateProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeOrder
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string FileName { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string PrimaryContact { get; set; }
        public string AvtexContact { get; set; }
        public Nullable<bool> SW { get; set; }
        public Nullable<bool> HW { get; set; }
        public Nullable<bool> PSO { get; set; }
        public Nullable<bool> OTHER { get; set; }
        public Nullable<bool> FixedBid { get; set; }
        public string CustomerName { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Email { get; set; }
        public string CustomerPO { get; set; }
        public string SoftwareLevel { get; set; }
        public string PricingQuote { get; set; }
        public string RequestedWork { get; set; }
        public string ShippingInfo { get; set; }
        public Nullable<bool> CrmOppCreated { get; set; }
    
        public virtual ChangeOrderStatu ChangeOrderStatu { get; set; }
    }
}
